### ISSUE TITLE
Ctrl+Backspace doesn't work

### ISSUE THREAD

**Issue by Laksen** [parmaja/miniedit#39]
Ctrl+Delete works as expected. It would be nice to have Ctrl+Backspace do the same just in the opposite direction.

**Comment by zaher** [comment]
Ctrl+Delete not works for me, I added it in this commit, while Ctrl+Backspace is work as deleting last word.

https://github.com/parmaja/miniedit/commit/5d971492715ee958415b51d71a4c4b4c28062b97

**Comment by Laksen** [comment]
Right. It's working nicely now.
